# Generated by Django 5.2.1 on 2025-07-02 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_classsession_attendancerecord_classtest_exam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
